---
#
# This dockerfile eases development:
#
# Create a .env file with the current user's UID and GID:
#   echo -e "UID=$(id -u)\nGID=$(id -g)" > .env
#
# Development environment:
#   docker-compose up -d dev
#
# Local API testing environment:
#   docker-compose up -d api-data-tls
#   open https://localhost/ui/
#
# Spin latest built images from GitHub Container Registry:
#   docker-compose up -d api-data-public-tls
#
services:
  dev:
    build:
      context: .
      target: dev
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /code
    volumes:
    - .:/code

  test:
    build:
      context: .
      target: test
    user: "${UID:-1000}:${GID:-1000}"

  api-data: &api
    build:
      context: .
      dockerfile: apiv1/Dockerfile
      target: data-api
    user: "${UID:-1000}:${GID:-1000}"
    restart: no
    environment:
    # App configuration.
    - HARVEST_DB=https://raw.githubusercontent.com/teamdigitale/dati-semantic-harvest/refs/heads/harvest/vocabularies.db
    - API_BASE_URL=https://localhost
    - PREDECESSOR_BASE_URL=https://schema.gov.it/api/vocabularies
    - CORS_ORIGINS=*
    # Uvicorn configuration.
    - UVICORN_WORKERS=4
    - UVICORN_LOG_LEVEL=debug
    ports:
    - "8001:8080"
    # Allow for downloading the harvest database and for testing the API from the host machine.
    working_dir: /tmp
    volumes:
    - ./apiv1/tests/data/:/data:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  api-data-tls: &tls
    image: docker.io/caddy:2
    ports:
    - "443:443"
    volumes:
    - ./tests/data/Caddyfile.api-data:/etc/caddy/Caddyfile:ro
    - caddy_deleteme:/data
    depends_on:
    - api-data

  api-data-public:
    <<: *api
    build: {}
    image: ghcr.io/teamdigitale/dati-semantic-csv-apis-data:latest

  api-data-public-tls:
    <<: *tls
    volumes:
    - ./tests/data/Caddyfile.api-data-public:/etc/caddy/Caddyfile:ro
    - caddy_deleteme:/data
    depends_on:
    - api-data-public

volumes:
  caddy_deleteme:
