#
# Entrypoint to test this project.
# Run tests with:
#
# $ tox -e py3
#
# Run APIs with:
#
# API_PORT=9000 tox -e api -- catalog
# API_PORT=9001 tox -e api -- data
#
[tox]
envlist = py312

# By default, we do not publish a module.
skipsdist=True

[testenv]
deps =
  -r requirements.txt
  -r requirements-dev.txt

# Uncomment here to set an extra PIP_INDEX_URL
# setenv =
#    PIP_EXTRA_INDEX_URL = https://mypypiserver.org

passenv =
  API_PORT

setenv =
  PYTHONPATH=:.:

# To show pytest logs in console, use
#   tox -- --log-cli-level=DEBUG
commands =
  python3 -m pytest {posargs}

[testenv:help]
deps = .

commands =
  python -m tools.commands --help
  python -m tools.commands jsonld --help
  python -m tools.commands jsonld create --help
  python -m tools.commands jsonld validate --help
  python -m tools.commands datapackage create --help
  python -m tools.commands datapackage validate --help
  python -m tools.commands csv --help
  python -m tools.commands csv create --help
  python -m tools.commands csv validate --help

[testenv:coverage]
commands =
  coverage run -m pytest {posargs} --cov --color=yes --cov-report term-missing --cov-report xml:coverage.xml --junitxml=report.xml

[testenv:report]
commands =
  coverage report
  coverage html

[coverage:run]
source = tools
# See https://coverage.readthedocs.io/en/latest/branch.html#branch
branch = True
omit =
  # Ignore the generated code.
  # tools/models/_generated/*
  # Ignore CLI entry point.
  tools/commands/
  apiv1/openapi/

[coverage:report]
# Show missing lines.
show_missing = True
skip_empty = True
precision = 2
omit =
  {[coverage:run]omit}
# From https://coverage.readthedocs.io/en/latest/config.html#sample-file
# Regexes for lines to exclude from consideration
exclude_also =
    # Don't complain about missing debug-only code:
    def __repr__
    if self\.debug

    # Don't complain if tests don't hit defensive assertion code:
    raise AssertionError
    raise NotImplementedError

    # Don't complain if non-runnable code isn't run:
    if 0:
    if __name__ == .__main__.:
    if (typing\.)?TYPE_CHECKING:

    # Don't complain about abstract methods, they aren't run:
    @(abc\.)?abstractmethod


#
# To run the stub API server, run:
#  tox -e run-api
#
[testenv:run-api]
deps =
  -r apiv1/requirements.txt

setenv =
  VOCABULARIES_DATAFILE = {toxinidir}/tests/api/vocabularies.linkset.yaml

commands =
  python -m {posargs}


[testenv:api]
toxworkdir = {toxinidir}/apiv1/.tox
changedir = {toxinidir}/apiv1
deps =
  -r apiv1/requirements.txt
  -r apiv1/requirements-dev.txt

setenv =
  PYTHONPATH = :.:..:
commands =
  python -m pytest {posargs}


[testenv:build]
allowlist_externals =
  rm
  sh
  dist/schema_gov_it_tools.bin

deps =
  .
  wheel
  pyinstaller

commands =
  rm -rf build dist

  sh -c 'commit=$(git rev-parse --short=8 HEAD); printf "%s\n\nBUILD_COMMIT = \"%s\"\n" "\"\"\"Build metadata for CLI version reporting.\"\"\"" "$commit" > "{toxinidir}/tools/_build_info.py"'

  pyinstaller --specpath build/ --clean \
  --onefile  \
  --add-data "{toxinidir}/tools/data:tools/data" \
  --name schema_gov_it_tools.bin tools/commands/__main__.py

  dist/schema_gov_it_tools.bin --help



[testenv:release]
# Release with tox via:
#
#    tox -e release -- $PARAMETERS
#
# passing the repo references you would set via
# twine, eg:
#  --repository-url https://test.pypi.org/legacy/
#
# To pass
deps =
  build
  twine
  wheel

# Limit TWINE_* to this section.
passenv =
  TWINE_USERNAME
  TWINE_PASSWORD
  TWINE_REPOSITORY_URL

commands =
#  rm dist -rf
  python -m build  # sdist, or whatever
  twine upload {posargs} dist/*


# Uncomment the following section if you want to
#  test the installation on the test pypi
# [testenv:test-release]
#commands =
#  pip install --index-url=https://test.pypi.org/simple

#
# Tools configuration.
#
[flake8]
# Ignore long lines in flake8 because
#   they are managed by black and we
#   want to support links.
max-line-length = 150
# Disable E203 because black correctly handles whitespaces before ':'.
extend-ignore = E203
