import functools
import logging
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import IO

import click
import yaml

from tools.base import InvalidFrameError

log = logging.getLogger(__name__)


def _cli_version() -> str:
    try:
        return version("dati-semantic-apis")
    except PackageNotFoundError:
        return "0+dev"


def yaml_dump(data: dict, stream: IO) -> None:
    """Write YAML to stream with a trailing version comment."""
    yaml.safe_dump(data, stream, allow_unicode=True, indent=2, sort_keys=True)
    stream.write(f"# Generated by dati-semantic-apis {_cli_version()}\n")


def handle_invalid_frame_error(func):
    """Decorator that catches InvalidFrameError, logs it, echoes involved files, and exits with error."""

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except InvalidFrameError as e:
            log.exception("Invalid frame error")
            files = [v for v in kwargs.values() if isinstance(v, Path)]
            for f in files:
                click.secho(f"✗ File: {f}", fg="red", err=True)
            click.secho(f"✗ Invalid frame: {e}", fg="red", err=True)
            click.secho(
                "  Hint: run `help dump-schema` to see the expected frame schema.",
                fg="yellow",
                err=True,
            )
            raise click.exceptions.Exit(1) from e

    return wrapper


def check_output_file(output: Path, force: bool) -> None:
    """Abort if output file exists and --force is not set."""
    if output.exists():
        if not force:
            click.secho(
                f"✗ Error: Output file {output} already exists. Use --force/-f to overwrite.",
                fg="red",
                err=True,
            )
            raise click.Abort()
        log.debug("Overwriting existing file: %s", output)
