components:
  schemas:
    Item:
      example:
        id: '01'
        label: COLTIVAZIONI AGRICOLE E PRODUZIONE DI PRODOTTI ANIMALI, CACCIA E SERVIZI
          CONNESSI
        level: '2'
        parent:
        - id: A
          uri: A
        uri: '01'
        vocab:
        - uri: ../ateco-2007-2022
      properties:
        id:
          minLength: 1
          pattern: ^[A-Za-z0-9._/-]+$
          type: string
        label:
          maxLength: 500
          minLength: 1
          type: string
        level:
          type: string
        parent:
          items:
            properties:
              id:
                type: string
              uri:
                format: uri-reference
                type: string
            required:
            - id
            - uri
            type: object
          maxItems: 100
          minItems: 0
          type: array
        uri:
          format: uri-reference
          type: string
        vocab:
          items:
            properties:
              uri:
                format: uri-reference
                type: string
            required:
            - uri
            type: object
          maxItems: 100
          minItems: 0
          type: array
      required:
      - id
      - label
      - level
      - parent
      - uri
      - vocab
      type: object
      x-jsonld-context:
        '@base': https://w3id.org/italia/stat/controlled-vocabulary/economy/ateco-2007-2022/
        '@vocab': https://w3id.org/italia/stat/controlled-vocabulary/economy/ateco-2007-2022/
        clvapit: https://w3id.org/italia/onto/CLV/
        covapit: https://w3id.org/italia/onto/COV/
        dct: http://purl.org/dc/terms/
        id:
          '@id': skos:notation
        label:
          '@id': skos:prefLabel
        level:
          '@id': clvapit:hasRankOrder
          '@type': xsd:int
        parent:
          '@container': '@set'
          '@context':
            uri: '@id'
          '@id': skos:broader
        skos: http://www.w3.org/2004/02/skos/core#
        uri: '@id'
        vocab:
          '@container': '@set'
          '@context':
            uri: '@id'
          '@id': skos:inScheme
        xkos: http://rdf-vocabulary.ddialliance.org/xkos#
        xsd: http://www.w3.org/2001/XMLSchema#
      x-jsonld-type: covapit:PrivateOrgActivityType
      x-validation:
        error_count: 0
        errors: []
        valid: true
info:
  contact:
    email: ndc-segr-tec@istat.it
    name: Segreteria Tecnica Istat - Progetto PNRR National Data Catalog
    url: https://w3id.org/italia/data/public-organization/ISTAT
  description: 'Classificazione delle attività economiche, adottata dall''Istat a
    partire dal 1° gennaio 2008. L''Ateco 2007 è la versione nazionale della classificazione
    Nace Rev. 2 definita in ambito europeo che, a sua volta, deriva da quella definita
    a livello Onu (Isic Rev. 4). La classificazione Ateco 2007 presenta le varie attività
    economiche raggruppate, dal generale al particolare, in sezioni (21), divisioni
    (88), gruppi (272), classi (615), categorie (996) e sottocategorie (1.224). Diversamente
    dalle precedenti versioni della classificazione, non sono più presenti le sottosezioni
    precedentemente individuate dalle due lettere.


    ## Metadata:


    URI: https://w3id.org/italia/stat/controlled-vocabulary/economy/ateco-2007-2022

    Keywords: ATECO, Ateco2007, Attività Economica, Classificazione


    '
  title: Ateco 2007 - Classificazione delle attività economiche - Aggiornamento 2022
  version: versione 2007 - Aggiornamento 2022
  x-agencyId: istat
  x-keyConcept: ateco-2007-2022
  x-summary: ''
openapi: 3.0.0
paths: {}
servers: []
# Generated by dati-semantic-apis 0.0.14.dev0+gcb3cace23.d20260408
