components:
  schemas:
    Item:
      example:
        id: '11110101'
        label_it: Idrogeno
        level: 3
        parent:
        - id: '1.1'
          url: https://w3id.org/italia/work-accident/controlled-vocabulary/adm_serv/agente_causale/gruppo/1.1
        url: https://w3id.org/italia/work-accident/controlled-vocabulary/adm_serv/agente_causale/agente/11110101
        vocab:
        - url: https://w3id.org/italia/work-accident/controlled-vocabulary/adm_serv/agente_causale
      properties:
        id:
          minLength: 1
          pattern: ^[A-Za-z0-9._-]+$
          type: string
        label_it:
          maxLength: 500
          minLength: 1
          type: string
        level:
          maximum: 10
          minimum: 0
          type: integer
        parent:
          items:
            properties:
              id:
                type: string
              url:
                format: uri-reference
                type: string
            required:
            - id
            - url
            type: object
          maxItems: 100
          minItems: 0
          type: array
        url:
          format: uri-reference
          type: string
        vocab:
          items:
            properties:
              url:
                format: uri-reference
                type: string
            required:
            - url
            type: object
          maxItems: 100
          minItems: 0
          type: array
      required:
      - id
      - label_it
      - level
      - parent
      - url
      - vocab
      type: object
      x-jsonld-context:
        '@vocab': https://w3id.org/italia/work-accident/controlled-vocabulary/adm_serv/
        INAILService: https://w3id.org/italia/work-accident/onto/adm_serv/
        clvapit: https://w3id.org/italia/onto/CLV/
        dct: http://purl.org/dc/terms/
        id:
          '@id': skos:notation
        label_it:
          '@id': skos:prefLabel
          '@language': it
        level:
          '@id': xkos:depth
          '@type': xsd:integer
        parent:
          '@container': '@set'
          '@context':
            id: skos:notation
            url: '@id'
          '@id': skos:broader
        skos: http://www.w3.org/2004/02/skos/core#
        url: '@id'
        vocab:
          '@container': '@set'
          '@context':
            url: '@id'
          '@id': skos:inScheme
        xkos: http://rdf-vocabulary.ddialliance.org/xkos#
        xsd: http://www.w3.org/2001/XMLSchema#
      x-jsonld-type: INAILService:AgenteCausaleINAIL
      x-validation:
        error_count: 0
        errors: []
        valid: true
info:
  contact:
    email: fake@example.com
    name: Fake Name
    url: https://w3id.org/italia/work-accident/data/organization/inail
  description: Decodifica dell'agente, lavorazione, o esposizione che puo' essere
    causa o concausa di malattia
  title: Vocabolario Controllato sulla classificazione degli agenti causali adottata
    dall'INAIL
  version: '0.5'
  x-agencyId: inail
  x-keyConcept: agente_causale
  x-summary: ''
openapi: 3.0.0
paths: {}
servers: []
