components:
  schemas:
    Item:
      example:
        definition: Diploma conseguito con l’ordinamento precedente alla Riforma delle
          Accademie di belle arti, dell’Accademia nazionale di danza, dell’Accademia
          nazionale di arte drammatica, degli Istituti superiori per le industrie
          artistiche, dei Conservatori di musica e degli Istituti di musica pareggiati
          (legge 508 del 1999 e successivo Decreto 212 del 2002).
        id: ACO
        label: Diploma di Accademia di Belle Arti, Danza, Arte Drammatica, ISIA, ecc.
          Conservatorio (vecchio ordinamento)
        label_en: Academy Conservatory old programme
        level: '1'
        uri: ACO
        vocab:
        - uri: education-level
      properties:
        definition:
          minLength: 1
          type: string
        id:
          minLength: 1
          pattern: ^[A-Za-z0-9._/-]+$
          type: string
        label:
          maxLength: 500
          minLength: 1
          type: string
        label_en:
          maxLength: 500
          minLength: 1
          type: string
        level:
          type: string
        uri:
          format: uri-reference
          type: string
        vocab:
          items:
            properties:
              uri:
                format: uri-reference
                type: string
            required:
            - uri
            type: object
          maxItems: 100
          minItems: 0
          type: array
      required:
      - definition
      - id
      - label
      - label_en
      - level
      - uri
      - vocab
      type: object
      x-jsonld-context:
        '@base': https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level/
        clvapit: https://w3id.org/italia/onto/CLV/
        cpvapit: https://w3id.org/italia/onto/CPV/
        dct: http://purl.org/dc/terms/
        definition:
          '@id': skos:definition
          '@language': it
        id:
          '@id': skos:notation
        label:
          '@id': skos:prefLabel
          '@language': it
        label_en:
          '@id': skos:prefLabel
          '@language': en
        level:
          '@id': clvapit:hasRankOrder
        skos: http://www.w3.org/2004/02/skos/core#
        uri: '@id'
        vocab:
          '@container': '@set'
          '@context':
            '@base': https://w3id.org/italia/controlled-vocabulary/classifications-for-people/
            uri: '@id'
          '@id': skos:inScheme
      x-jsonld-type: cpvapit:EducationLevel
      x-validation:
        error_count: 0
        errors: []
        valid: true
info:
  contact:
    email: info@dati.gov.it
    name: banche dati e open data
    url: http://spcdata.digitpa.gov.it/browse/page/Amministrazione/ISTAT
  description: 'Questo è il vocabolario controllato sul grado di istruzione/titoli
    di studio delle persone.


    ## Metadata:


    URI: https://w3id.org/italia/controlled-vocabulary/classifications-for-people/education-level

    Keywords: Education, Education Level, Grado Istruzione, Istruzione, Titolo di
    studio


    '
  title: Vocabolario Controllato Grado di Istruzione/Titoli di Studio
  version: Current available version - a new version of the classification is under
    definition by the Italian National Institute of Statistics - ISTAT. In this version
    the codes have been updated deleting previous ZZ_ prefix
  x-agencyId: istat
  x-keyConcept: education-level
  x-summary: ''
openapi: 3.0.0
paths: {}
servers: []
# Generated by dati-semantic-apis 0.0.19
