"""Unit tests for tools.commands.utils."""

import io

from tools.commands.utils import _cli_version, yaml_dump


def test_yaml_dump_appends_version_comment():
    data = {"foo": "bar"}
    stream = io.StringIO()
    yaml_dump(data, stream)
    content = stream.getvalue()
    assert content.endswith(
        f"# Generated by dati-semantic-apis {_cli_version()}\n"
    ), f"Expected version comment at end of output, got:\n{content}"


def test_yaml_dump_valid_yaml_before_comment():
    import yaml

    data = {"key": "value", "nested": {"a": 1}}
    stream = io.StringIO()
    yaml_dump(data, stream)
    lines = stream.getvalue().splitlines()
    yaml_lines = [line for line in lines if not line.startswith("#")]
    parsed = yaml.safe_load("\n".join(yaml_lines))
    assert parsed == data
