# generated by datamodel-codegen:
#   filename:  vocabularies.yaml
#   timestamp: 2026-04-24T16:10:40+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class IdString(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=["11160204"],
            max_length=128,
            pattern="^[A-Za-z0-9._/-]{1,128}$",
        ),
    ]
    """
    An identifier string that constrains
    the length and characters of the input.

    This is a substring match on the corresponding field of
    the vocabulary metadata.
    """


class LanguageTagShort(RootModel[str]):
    root: Annotated[
        str,
        Field(
            examples=["en"], max_length=2, min_length=2, pattern="^[a-z]{2}$"
        ),
    ]
    """
    ISO 639-1 2-letter language code
    """


class TitleString(RootModel[str]):
    root: Annotated[str, Field(max_length=200, pattern="^[\\s\\S]{1,200}$")]
    """
    A short string used for titles and similar fields. The underlying regexp allows for newlines and other whitespace characters.
    It is defined to accept all characters used in RDF vocabularies.
    """


class TextFilter(RootModel[str]):
    root: Annotated[
        str, Field(max_length=128, pattern="^[A-Za-z0-9 ._:/-]{1,128}$")
    ]
    """
    A text filter that constrains
    the length and characters of the input.

    This is a substring match on the corresponding field of
    the vocabulary metadata.
    """


class DumpResponse(RootModel[bytes]):
    root: bytes


class Limit(RootModel[int]):
    root: Annotated[int, Field(examples=[50], ge=0, le=200)] = 20
    """
    A limit for pagination.
    This value is bounded by the maximum number of items that can be returned by the API.
    """


class Url(RootModel[str]):
    root: Annotated[
        str,
        Field(examples=["/vocabularies/v1/agid/agentecausale/openapi.yaml"]),
    ]
    """
    An URL that is either absolute or relative.
    """


class URI(RootModel[AnyUrl]):
    root: Annotated[
        AnyUrl,
        Field(
            examples=[
                "https://schema.gov.it/vocabularies/v1/agid/agentecausale/"
            ]
        ),
    ]
    """
    An absolute URI.
    """


class ParentItem(BaseModel):
    uri: str


class VocabItem(BaseModel):
    uri: str


class Item(BaseModel):
    id: IdString
    label: Annotated[str, Field(max_length=500, min_length=1)]
    parent: Annotated[
        list[ParentItem] | None, Field(max_length=100, min_length=0)
    ] = None
    uri: str
    href: URI | None = None
    vocab: Annotated[
        list[VocabItem] | None, Field(max_length=100, min_length=0)
    ] = None


class Type(Enum):
    application_openapi_yaml = "application/openapi+yaml"
    application_openapi_json = "application/openapi+json"


class ServiceDescription(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    href: URI
    type: Type
    """
    Media type of the service description document.

    In the current dcatapit, dcterms:format references
    the URI of the publication office, that references
    the media type of the document.
    Since we need to specify the media type directly,
    we used the IANA media type registry as the base URI.
    """


class Type1(Enum):
    application_ld_json = "application/ld+json"


class ServiceMeta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    href: URI
    type: Type1


class Link(BaseModel):
    href: URI


class Offset(RootModel[int]):
    root: Annotated[int, Field(examples=[0], ge=0, le=100000)] = 0
    """
    An offset for pagination.

    This API supports at maximum ~100_000 items vocabularies.
    """


class AsciiText(RootModel[str]):
    root: Annotated[str, Field(max_length=32, pattern="^[a-zA-Z0-9-_]{1,32}$")]
    """
    An ASCII text string that constrains
    the length and characters of the input.

    This is a substring match on the corresponding field of
    the vocabulary metadata.
    """


class Problem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        AnyUrl | None,
        Field(
            examples=[
                "https://schema.gov.it/vocabularies/v1/agid/agentecausale/"
            ]
        ),
    ] = "about:blank"
    """
    An absolute URI.
    """
    title: Annotated[str, Field(max_length=128)]
    status: Annotated[int, Field(ge=100, le=599)]
    detail: Annotated[str | None, Field(max_length=1024)] = None
    instance: Url | None = None


class PaginatedResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    limit: Annotated[Limit | None, Field(validate_default=True)] = 20
    next_cursor: IdString | None = None
    """
    Cursor for pagination.

    It is the `id` of the last item in the previous page.
    the next page can be retrieved by using this value as the `cursor` query parameter.
    If there are no more items to return, this field is null.
    """
    items: Annotated[list[Item] | None, Field(max_length=200, min_length=0)] = (
        None
    )


class APIDistribution(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    about: Annotated[
        URI,
        Field(
            examples=[
                "https://w3id.org/italia/controlled-vocabulary/classifications-for-organizations/ateco-2007"
            ]
        ),
    ]
    """
    The URI of the vocabulary concept being published by this API.
    """
    href: Annotated[
        URI,
        Field(
            examples=[
                "https://schema.gov.it/api/vocabularies/v1/istat/ateco-2007"
            ]
        ),
    ]
    """
    URL of the API endpoint for the vocabulary. It is the identifier of the API.
    """
    title: TitleString
    """
    Human-readable title extracted from the vocabulary metadata, (e.g., skos:prefLabel).
    """
    field_concept: Annotated[
        TitleString | None,
        Field(alias="_concept", deprecated=True, examples=["ateco-2007"]),
    ] = None
    """
    The key concept of the vocabulary, if any.

    This is extracted from the vocabulary metadata
    and can be used for filtering and searching.

    For example, for a classification vocabulary,
    this is the concept that represents the classification itself.

    :warning: Do we need this? URIs are more stable.
    """
    field_vocabulary_type: Annotated[
        URI | None,
        Field(
            alias="_vocabulary_type",
            deprecated=True,
            examples=["http://purl.org/adms/assettype/CodeList"],
        ),
    ] = None
    """
    The type of the vocabulary, if any.
    This is extracted from the vocabulary metadata
    :warning: Do we need this?.
    """
    hreflang: Annotated[
        list[LanguageTagShort] | None,
        Field(examples=[["it"]], max_length=10, min_length=1),
    ] = None
    """
    Language codes supported by the vocabulary
    (ISO 639-1 two-letter codes),
    to be compatible with the `hreflang` link attribute
    defined in RFC 8288.
    """
    author: URI
    """
    Author/publisher URI (RFC 4287) as extracted from the vocabulary metadata.
    """
    description: Annotated[
        str, Field(max_length=4000, pattern="^[\\s\\S]{1,4000}$")
    ]
    """
    Human-readable description extracted from the vocabulary metadata,
    (e.g., skos:definition).
    This is not associated with any Link Relation.

    The underlying regexp allows for newlines and other whitespace characters.
    """
    version: Annotated[
        str | None, Field(max_length=100, pattern="^.{1,100}$")
    ] = None
    """
    Version identifier.

    While this should probably be a short,
    human-readable string
    such as a semantic version or a date,
    we allow for longer strings to avoid issues with
    long text strings.

    Reasonable long version strings could
    be 68-character sha256 hashes.
    """
    service_desc: Annotated[
        list[ServiceDescription] | None,
        Field(alias="service-desc", max_length=1, min_length=1),
    ] = None
    """
    Service description links (RFC 8631) referencing the OpenAPI specification of the vocabulary API.
    """
    service_meta: Annotated[
        list[ServiceMeta] | None,
        Field(alias="service-meta", max_length=1, min_length=1),
    ] = None
    """
    Metadata about the vocabulary API service.
    """
    predecessor_version: Annotated[
        list[Link] | None,
        Field(alias="predecessor-version", max_length=1, min_length=1),
    ] = None
    """
    Link to the previous version of this vocabulary API,
    if any.
    """


class APICatalog(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    anchor: URI | None = None
    """
    The canonical reference to the API Catalog
    URL. This is for future use, in case we want to spread
    the current API Catalog URL across multiple URLs.
    """
    api_catalog: Annotated[URI, Field(alias="api-catalog")]
    """
    The current API Catalog URL.
    """
    item: Annotated[list[APIDistribution], Field(max_length=100, min_length=0)]
    """
    List of API distributions published by
    this API Catalog. The size of this list is limited
    to 100 items per request. Consumer can use pagination
    to retrieve the full list of items, or query for specific
    items.
    """
    total_count: Annotated[Offset | None, Field(validate_default=True)] = 0
    count: Annotated[Limit | None, Field(validate_default=True)] = 20
    limit: Annotated[Limit | None, Field(validate_default=True)] = 20
    offset: Annotated[Offset | None, Field(validate_default=True)] = 0


class Linkset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    linkset: Annotated[list[APICatalog], Field(max_length=10, min_length=1)]
    """
    List of API Catalogs. The size of this list is limited
    to 10 items because no more that 10 API Catalogs are expected.

    For this API, it is actually always 1.
    """
